@startuml
skinparam classAttributeIconSize 0
class Caller {
    - moneyAmount : float
    + AddMoney() : void
    + StoreMoney() : float
    + Use(Phonebooth phonebooth) : void

}
class Phonebooth {
    - price : float
    - number : int
    + Call() : bool
    + ReturnMoney() : float
    - RemoveMoney() : float
}

class Receiver {
    - number : string
    - phonebooth[] : Phonebooth
    + HangUp() : void
}
Caller --|> Receiver

Caller "1" --> "1" Phonebooth
Phonebooth "1" -- "1,*" Receiver

note right of Receiver
  The cardinality of the link Phonebooth -> Reciever
  is a 1,* because the Reciever can be a number like 911
end note

@enduml