@startuml
skinparam classAttributeIconSize 11
class Caller {
    - number : int
    - moneyAmount : float
    - phonebooth : Phonebooth
    + AddMoney() : void
    + StoreMoney() : string
    + Use() : void

}
class Phonebooth {
    - price : float
    - reciver : Reciever
    + Call() : bool
    + ReturnMoney() : float
}

class Reciever {
    - number : int
    - phonebooth[] : Phonebooth
    + HangUp() : void
}

Caller "1" --> "1" Phonebooth
Phonebooth "1" -- "1,*" Reciever

note right of Reciever
  The cardinality of the link Phonebooth -> Reciever
  is a 1,* because the Reciever can be a number like 911
end note

@enduml