@startuml
:appelant: as caller 
:cabine: as telephone
:recevant: as reciever


rectangle Publiphone {
usecase "ajouter de l'argent" as add
usecase utiliser as use
usecase appeler as call
usecase raccrocher as hangup
usecase "rendre de l'argent" as return

}
caller --> add
add ..> use : extends
use --> telephone
telephone --> call
call --> reciever
reciever --> hangup
telephone --> return
return --> caller
hangup --> telephone 
@enduml